// "use client"
import Head from 'next/head';
// import React, { useState, useEffect } from 'react';
import Deals from '../components/deals';
import Services from '../components/services';
import Review from '../components/review';

import Footer from '@/components/footer';
import Hero from '@/components/hero';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>CampusRentals </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-bgDark">
        <Hero
          address="225 S 1st St Brooklyn, NY 11211"
          phone="7089585990"
          email="gouravojha214@gmail.com"
        />
        <Services />
        <Deals />
        <Review />
        <Footer />
      </div>
    </>
  );
};

export default HomePage;
